//! Build script: generate the embedded preset list from `presets/*.toml` so
//! shipping a preset is dropping a file, not editing Rust (ADR-0022, Plan 0021).
//!
//! `include_str!` cannot expand a directory — it takes only a string literal —
//! so the list was hand-maintained. We instead glob `presets/` here at build
//! time and emit a generated `EMBEDDED` slice whose entries are still
//! `include_str!(<absolute path>)` tuples, so rustc embeds the bytes exactly as
//! a hand-written array would. Zero dependency: a `read_dir` + extension filter
//! is all it takes.

use std::path::PathBuf;

fn main() {
    // Resolve `presets/` from the crate manifest dir (core/..), never the CWD,
    // so generation is correct under `cargo build` from anywhere, CI, and
    // rust-analyzer. Absolute `include_str!` paths (built from the same root)
    // also resolve regardless of where in OUT_DIR the generated file lands.
    let manifest_dir = PathBuf::from(
        std::env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by cargo"),
    );
    let presets_dir = manifest_dir
        .parent()
        .expect("the core crate has a workspace-root parent")
        .join("presets");

    // Retrigger generation whenever the directory changes (a preset added or
    // removed). A directory `rerun-if-changed` scans its contents, and each file
    // is registered below too, so an edit to a single preset also retriggers.
    println!("cargo:rerun-if-changed={}", presets_dir.display());

    // Collect `*.toml` filenames; anything else (e.g. `presets/README.md`) is
    // skipped by the extension filter. A missing/empty dir yields an empty slice
    // (it compiles; `default_presets()` returning empty is already tolerated).
    let mut files: Vec<String> = Vec::new();
    if let Ok(entries) = std::fs::read_dir(&presets_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().is_some_and(|ext| ext == "toml")
                && let Some(name) = path.file_name().and_then(|n| n.to_str())
            {
                println!("cargo:rerun-if-changed={}", path.display());
                files.push(name.to_string());
            }
        }
    }
    // Deterministic embedded order (and thus the default cycle order),
    // build-to-build — matching the on-disk `load_dir` filename sort.
    files.sort();

    // `{:?}` on the filename and the absolute path emits a properly-escaped Rust
    // string literal (backslashes and quotes handled), so the generated file is
    // valid on Windows paths too.
    // The `///` doc satisfies core's `#![warn(missing_docs)]` for this generated
    // `pub` item (a doc comment can't be attached where `include!` is invoked).
    let mut out = String::from(
        "// @generated by core/build.rs from presets/*.toml (ADR-0022). Do not edit.\n\
         /// The shipped example presets, generated from `presets/*.toml` by\n\
         /// `core/build.rs` (ADR-0022): `(filename, contents)` tuples, sorted by\n\
         /// filename, each embedded via `include_str!`.\n\
         pub static EMBEDDED: &[(&str, &str)] = &[\n",
    );
    for name in &files {
        let abs = presets_dir.join(name);
        let abs = abs.to_string_lossy();
        out.push_str(&format!("    ({name:?}, include_str!({abs:?})),\n"));
    }
    out.push_str("];\n");

    let out_dir =
        PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR is set by cargo"));
    std::fs::write(out_dir.join("embedded_presets.rs"), out)
        .expect("write generated embedded_presets.rs");
}
